services:
  hel-prod-apps-coolify:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: hel-prod-apps-coolify
    restart: unless-stopped
    environment:
      TZ: 'Europe/Brussels'
      APP_ID: ${COOLIFY_APP_ID}
      APP_KEY: ${COOLIFY_APP_KEY}
      APP_URL: ${COOLIFY_APP_URL}
      DB_CONNECTION: pgsql
      DB_HOST: hel-prod-apps-coolify-db
      DB_DATABASE: ${COOLIFY_DB_NAME}
      DB_USERNAME: ${COOLIFY_DB_USER}
      DB_PASSWORD: ${COOLIFY_DB_PASSWORD}
      REDIS_HOST: hel-prod-apps-coolify-redis
      PUSHER_HOST: hel-prod-apps-coolify-realtime
      PUSHER_BACKEND_HOST: hel-prod-apps-coolify-realtime
    volumes:
      - /var/lib/docker-compose/hel-prod-apps-coolify:/var/www/html/storage/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8000:8080"
    depends_on:
      - hel-prod-apps-coolify-db
      - hel-prod-apps-coolify-redis
      - hel-prod-apps-coolify-realtime

  hel-prod-apps-coolify-db:
    image: postgres:16-alpine
    container_name: hel-prod-apps-coolify-db
    restart: unless-stopped
    environment:
      TZ: 'Europe/Brussels'
      POSTGRES_DB: ${COOLIFY_DB_NAME}
      POSTGRES_USER: ${COOLIFY_DB_USER}
      POSTGRES_PASSWORD: ${COOLIFY_DB_PASSWORD}
    volumes:
      - /var/lib/docker-compose/hel-prod-apps-coolify-db:/var/lib/postgresql/data

  hel-prod-apps-coolify-redis:
    image: redis:7-alpine
    container_name: hel-prod-apps-coolify-redis
    restart: unless-stopped
    environment:
      TZ: 'Europe/Brussels'
    volumes:
      - /var/lib/docker-compose/hel-prod-apps-coolify-redis:/data

  hel-prod-apps-coolify-realtime:
    image: ghcr.io/coollabsio/coolify-realtime:latest
    container_name: hel-prod-apps-coolify-realtime
    restart: unless-stopped
    environment:
      TZ: 'Europe/Brussels'
      PUSHER_APP_ID: ${COOLIFY_PUSHER_APP_ID}
      PUSHER_APP_KEY: ${COOLIFY_PUSHER_APP_KEY}
      PUSHER_APP_SECRET: ${COOLIFY_PUSHER_APP_SECRET}
